@csrf
<div class="grid gap-5 sm:grid-cols-2">
    <div><label class="text-sm font-medium">Sport name</label><input name="name" required value="{{ old('name', $sport->name) }}" class="mt-1 block w-full rounded-lg border-slate-300"><x-input-error for="name" class="mt-1" /></div>
    <div><label class="text-sm font-medium">Catalogue status</label><select name="status" class="mt-1 block w-full rounded-lg border-slate-300"><option value="active" @selected(old('status', $sport->status ?: 'active') === 'active')>Active</option><option value="inactive" @selected(old('status', $sport->status) === 'inactive')>Inactive</option></select></div>
    <div><label class="text-sm font-medium">Participant type</label><select name="participant_type" class="mt-1 block w-full rounded border"><option value="team" @selected(old('participant_type', $editionSport?->participant_type) === 'team')>Team</option><option value="dual" @selected(old('participant_type', $editionSport?->participant_type) === 'dual')>Dual</option><option value="individual" @selected(old('participant_type', $editionSport?->participant_type) === 'individual')>Individual</option></select></div>
    <div><label class="text-sm font-medium">Game mechanic</label><select name="game_mechanic" class="mt-1 block w-full rounded border"><option value="single_elimination" @selected(old('game_mechanic', $editionSport?->game_mechanic) === 'single_elimination')>Single elimination</option><option value="double_elimination" @selected(old('game_mechanic', $editionSport?->game_mechanic) === 'double_elimination')>Double elimination</option><option value="round_robin" @selected(old('game_mechanic', $editionSport?->game_mechanic) === 'round_robin')>Round robin</option><option value="custom" @selected(old('game_mechanic', $editionSport?->game_mechanic) === 'custom')>Custom</option></select></div>
    <div class="sm:col-span-2"><label class="text-sm font-medium">Sport rules</label><textarea name="rules" class="mt-1 block w-full rounded border">{{ old('rules', $editionSport?->rules) }}</textarea><input type="hidden" name="configuration_status" value="{{ $editionSport?->status ?? 'preparation' }}"></div>
</div>
<div class="mt-6"><button class="rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white">{{ $submitLabel }}</button></div>
