@csrf
<div class="grid gap-5 sm:grid-cols-2">
    <div><label class="text-sm font-medium">Edition</label><select name="edition_id" required class="mt-1 block w-full rounded-lg border-slate-300"><option value="">Select edition</option>@foreach($editions as $edition)<option value="{{ $edition->id }}" @selected(old('edition_id', $event->edition_id) == $edition->id)>{{ $edition->name }} ({{ $edition->school_year }})</option>@endforeach</select></div>
    <div><label class="text-sm font-medium">Sport</label><input type="hidden" name="sport_id" value="{{ $event->sport_id }}"><div class="mt-1 rounded-lg border border-slate-300 bg-slate-50 px-3 py-2 text-sm text-slate-700">{{ $sport->name }}</div></div>
    <div><label class="text-sm font-medium">Competition type</label><select id="competition_type" name="competition_type" class="mt-1 block w-full rounded-lg border-slate-300"><option value="team" @selected(old('competition_type', $event->competition_type) === 'team')>Team</option><option value="dual" @selected(old('competition_type', $event->competition_type) === 'dual')>Dual</option><option value="individual" @selected(old('competition_type', $event->competition_type) === 'individual')>Individual</option></select><p class="mt-1 text-xs text-slate-500">Dual events support paired participants from the same team.</p></div>
    <div><label class="text-sm font-medium">Result mode</label><select name="result_mode" class="mt-1 block w-full rounded-lg border-slate-300">@foreach(['score'=>'Score','placement'=>'Placement','win_loss'=>'Win / loss','custom'=>'Custom'] as $value=>$label)<option value="{{ $value }}" @selected(old('result_mode', $event->result_mode ?: 'score') === $value)>{{ $label }}</option>@endforeach</select></div>
    <div id="capacity-field"><label class="text-sm font-medium">Maximum individual participants</label><input type="number" min="1" name="capacity" value="{{ old('capacity', $event->capacity) }}" class="mt-1 block w-full rounded-lg border-slate-300"><p class="mt-1 text-xs text-slate-500">Used only for individual events.</p></div>
    @isset($event->id)<div><label class="text-sm font-medium">Status</label><select name="status" class="mt-1 block w-full rounded-lg border-slate-300">@foreach(['draft','scheduled','live','completed','cancelled'] as $status)<option value="{{ $status }}" @selected(old('status', $event->status) === $status)>{{ ucfirst($status) }}</option>@endforeach</select></div>@endisset
</div>
<script>const typeSelect = document.getElementById('competition_type'); const capacityField = document.getElementById('capacity-field'); const toggleCapacity = () => capacityField.classList.toggle('hidden', typeSelect.value !== 'individual'); typeSelect.addEventListener('change', toggleCapacity); toggleCapacity();</script>
<div class="mt-6"><button class="rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white">{{ $submitLabel }}</button></div>
